# Generated by Django 3.2.4 on 2021-06-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('originplace', models.CharField(max_length=200)),
                ('outboundpartialdate', models.CharField(max_length=200)),
                ('destinationplace', models.CharField(max_length=200)),
                ('inboundpartialdate', models.CharField(max_length=200)),
            ],
        ),
    ]
