# Generated by Django 3.2.4 on 2021-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
        migrations.AddField(
            model_name='schedule',
            name='telephone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
