# Generated by Django 3.2.4 on 2021-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210702_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='originplace',
            field=models.CharField(default='Poland', max_length=200),
        ),
    ]
